sudo: false

# test on both linux and osx
os:
  - linux
  - osx

language: rust

# decreases build time (compilation)
cache: cargo

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

# run builds for all the trains (and more)
rust:
  - nightly
  - beta
  - stable

# load travis-cargo
before_script:
  - |
    cargo install rustfmt || true # cargo install fails if the package is already installed
    export PATH=$HOME/.cargo/bin:$PATH # rustfmt sometimes does not appear on the PATH
  - |
      export PYTHONUSERBASE=$HOME/.local &&
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      LOG_LEVEL=4 ./rust_build/build.sh &&
      travis-cargo test &&
      travis-cargo --only stable doc -- --markdown-playground-url='https://play.rust-lang.org'
after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  - travis-cargo --only stable doc-upload
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)

  # manually call kcov
  # workaround while travis-cargo doesn't pass correct arguments to kcov
  # see https://github.com/huonw/travis-cargo/pull/55
  - |
      if test $TRAVIS_OS_NAME = linux && ! rustc --version | grep -q 'beta\|nightly' ; then \
        # this installs kcov
        travis-cargo coveralls --no-sudo --verify
        ./kcov/build/src/kcov --verify \
                              --coveralls-id=$TRAVIS_JOB_ID \
                              --exclude-pattern=/.cargo \
                              target/kcov \
                              target/debug/builder_macro-*
      fi

env:
  global:
    # we don't user any nightly features right now
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  allow_failures:
    - rust: nightly
